Precommit for release 4.3

diff --git a/imgtest b/imgtest
--- a/imgtest
+++ b/imgtest
@@ -1,14 +1,14 @@
 #!/bin/bash
 ## file: imgtest
 ##
-## usage: imgtest [--refresh] symbol text opts
+## usage: imgtest [--regen] symbol text opts
 ##
 ## Compare a generated image against a proof image.
 ##
 REGEN=NO
-if [ "x$1" == x--refresh ] ; then
-	REGEN=YES
-	shift
+if [ "x$1" == x--regen ] ; then
+    REGEN=YES
+    shift
 fi
 
 sym="$1"
@@ -24,16 +24,16 @@ echo "$filename"
 status=$?
 
 if [ ! -f proofs/$filename -o $REGEN == YES ] ; then
-	cp -f tests/$filename proofs/$filename
+    cp -f tests/$filename proofs/$filename
 fi
 
 msg=$(./imgcmp proofs/$filename tests/$filename)
 
 (
 if [ ! -z "$msg" ] ; then
-	echo "<div class=\"main error\">"
+    echo "<div class=\"main error\">"
 else 
-	echo "<div class=\"main\">"
+    echo "<div class=\"main\">"
 fi
 echo "<h1>$filename</h1>"
 
@@ -57,13 +57,13 @@ console.log('postscript: ' + bwipp.readUInt32BE(16) + ' x ' + bwipp.readUInt32BE
 console.log('</div>');
 @EOF
 if [ ! -z "$msg" ] ; then
-	echo "<br><span>$msg</span>"
+    echo "<br><span>$msg</span>"
 fi
 echo "</div>"
 ) >> imgtests.html
 
 if [ ! -z "$msg" ] ; then
-	echo "$msg"
-	exit 1
+    echo "$msg"
+    exit 1
 fi
 exit 0
diff --git a/mkdist b/mkdist
--- a/mkdist
+++ b/mkdist
@@ -6,8 +6,8 @@
 ##
 COPYR=$(grep '% Copyright (c)' barcode.ps | sed -e 's,%,//,')
 if [ "x$COPYR" = x ] ; then
-	echo "Unable to find the copyright notice in barcode.ps" 1>&2
-	exit 1
+    echo "Unable to find the copyright notice in barcode.ps" 1>&2
+    exit 1
 fi
 
 ##
@@ -15,8 +15,8 @@ fi
 ##
 FILEV=$(grep '% Barcode Writer in Pure PostScript - Version' barcode.ps | sed -e 's,%,//,')
 if [ "x$FILEV" = x ] ; then
-	echo "Unable to find the version string in barcode.ps" 1>&2
-	exit 1
+    echo "Unable to find the version string in barcode.ps" 1>&2
+    exit 1
 fi
 
 ## What year is it?
@@ -25,7 +25,7 @@ YEAR="2011-$(date +%Y)"
 cat <<@EOF > dist/bwip-js.js
 // This file is part of the bwip-js project available at:
 //
-// 	  http://metafloor.github.io/bwip-js
+//    http://metafloor.github.io/bwip-js
 //
 // Copyright (c) $YEAR Mark Warren
 //
@@ -92,7 +92,7 @@ cat - <<@EOF >> $file
         module.exports = factory();
     } else {
         root.bwipjs = factory();
-	}
+    }
 }(typeof self !== 'undefined' ? self : this, function () {
 @EOF
 done
diff --git a/runtest b/runtest
--- a/runtest
+++ b/runtest
@@ -11,8 +11,8 @@
 ## a custom tests/barcode.ps that has the renderer code blocks commented out,
 ## leaving the rendering information on the stack for us to inspect.
 if [ ! -r tests/barcode.ps ] ; then
-	echo "runtest: tests/barcode.ps does not exist."
-	exit 1
+    echo "runtest: tests/barcode.ps does not exist."
+    exit 1
 fi
 
 sym="$1"
@@ -36,12 +36,12 @@ cat tests/barcode.ps - > tests/runtest.ps <<@EOF
 0 0 moveto
 ($pstext) ($opts) /$sym /uk.co.terryburton.bwipp findresource exec
 count { 
-	% Order of printing must match the nodejs code.
-	dup { exch (pixs) eq { == } { pop } ifelse } forall
-	dup { exch (sbs) eq { == } { pop } ifelse } forall
-	dup { exch (bbs) eq { == } { pop } ifelse } forall
-	dup { exch (bhs) eq { == } { pop } ifelse } forall
-	pop
+    % Order of printing must match the nodejs code.
+    dup { exch (pixs) eq { == } { pop } ifelse } forall
+    dup { exch (sbs) eq { == } { pop } ifelse } forall
+    dup { exch (bbs) eq { == } { pop } ifelse } forall
+    dup { exch (bhs) eq { == } { pop } ifelse } forall
+    pop
 } repeat
 @EOF
 
@@ -55,28 +55,28 @@ cat - <<@EOF > tests/nsed.js
 const fs = require('fs');
 
 function filt(line) {
-	process.stdout.write(
-		line.replace(/\d+(\.\d+)?/g, function(s) {
-			return (+s).toFixed(3).replace(/(\.000|00|0)$/, '');
-		})
-		.replace(/null/g, ''), 'binary');
+    process.stdout.write(
+        line.replace(/\d+(\.\d+)?/g, function(s) {
+            return (+s).toFixed(3).replace(/(\.000|00|0)$/, '');
+        })
+        .replace(/null/g, ''), 'binary');
 }
 
 let ptl = '';
 process.stdin.resume();
 process.stdin.setEncoding('binary');
 process.stdin.on('data', (data) => {
-	ptl += data.toString('binary');
-	let eol = ptl.indexOf('\n');
-	while (eol >= 0) {
-		filt(ptl.substr(0, eol+1));
-		ptl = ptl.substr(eol+1);
-		eol = ptl.indexOf('\n');
-	}
+    ptl += data.toString('binary');
+    let eol = ptl.indexOf('\n');
+    while (eol >= 0) {
+        filt(ptl.substr(0, eol+1));
+        ptl = ptl.substr(eol+1);
+        eol = ptl.indexOf('\n');
+    }
 });
 process.stdin.on('end', () => {
-	ptl && filt(ptl);
-	process.exit(0);
+    ptl && filt(ptl);
+    process.exit(0);
 });
 @EOF
 
@@ -89,36 +89,36 @@ node <<@EOF
 var bwipjs = require('.');
 
 try {
-	var stack = bwipjs.raw("$sym", "$jstext", "$opts");
+    var stack = bwipjs.raw("$sym", "$jstext", "$opts");
 } catch (e) {
-	// Example bwipp.raiseerror from ghostscript:
-	// 		Error: /bwipp.qrcodeNoValidSymbol in
-	//		Additional information: (No valid symbol available)
-	//		Current allocation mode is local
-	// raiseerror in bwipjs formats as:
-	//		Error: bwipp.qrcodeNoValidSymbol: No valid symbol available
-	// Make our output look like ghostscript's.
-	var msg = '' + e;
-	if (msg.indexOf('Error: bwipp.') >= 0) {
-		// Watch out for shell replacement of $-prefixed subst-markers!!!
-		console.log(msg.replace(/Error: bwipp\.([^:#]+)(?:#\d+)?:\s*(.*)$/,
-						'Error: /bwipp.\$1 in\n' +
-						'Additional information: (\$2)\n' +
-						'Current allocation mode is local'));
-	} else if (e.stack) {
-		console.log(e.stack);
-	} else {
-		console.log(e);
-	}
-	process.exit();
+    // Example bwipp.raiseerror from ghostscript:
+    //      Error: /bwipp.qrcodeNoValidSymbol in
+    //      Additional information: (No valid symbol available)
+    //      Current allocation mode is local
+    // raiseerror in bwipjs formats as:
+    //      Error: bwipp.qrcodeNoValidSymbol: No valid symbol available
+    // Make our output look like ghostscript's.
+    var msg = '' + e;
+    if (msg.indexOf('Error: bwipp.') >= 0) {
+        // Watch out for shell replacement of $-prefixed subst-markers!!!
+        console.log(msg.replace(/Error: bwipp\.([^:#]+)(?:#\d+)?:\s*(.*)$/,
+                        'Error: /bwipp.\$1 in\n' +
+                        'Additional information: (\$2)\n' +
+                        'Current allocation mode is local'));
+    } else if (e.stack) {
+        console.log(e.stack);
+    } else {
+        console.log(e);
+    }
+    process.exit();
 }
 // Order of printing must match the ghostscript code.
 for (var i = stack.length-1; i >= 0; i--) {
-	var o = stack[i];
-	if (o.pixs) { console.log('[' + o.pixs.join(' ') + ']'); }
-	if (o.sbs) { console.log('[' + o.sbs.join(' ') + ']'); }
-	if (o.bbs) { console.log('[' + o.bbs.join(' ') + ']'); }
-	if (o.bhs) { console.log('[' + o.bhs.join(' ') + ']'); }
+    var o = stack[i];
+    if (o.pixs) { console.log('[' + o.pixs.join(' ') + ']'); }
+    if (o.sbs) { console.log('[' + o.sbs.join(' ') + ']'); }
+    if (o.bbs) { console.log('[' + o.bbs.join(' ') + ']'); }
+    if (o.bhs) { console.log('[' + o.bhs.join(' ') + ']'); }
 }
 @EOF
 ) | sed -e 's/\([0-9]\)\.0\([^0-9]\)/\1\2/g' -e 's/\(\.[0-9][0-9][0-9]\)[0-9][0-9]*/\1/g' > $JSOUT
@@ -127,14 +127,14 @@ for (var i = stack.length-1; i >= 0; i--) {
 ## diff ignoring whitespace (-b) differences. 
 diff -qb $GSOUT $JSOUT
 if [ $? != 0 ] ; then
-	echo "!!!!"
-	echo "!!!! ERROR ON $sym ($text) ($opts)"
-	echo "!!!! BWIPP OUTPUT ($GSOUT):"
-	cat $GSOUT
-	echo "!!!! BWIP-JS OUTPUT ($JSOUT):"
-	cat $JSOUT
-	echo "!!!!"
-	exit 1
+    echo "!!!!"
+    echo "!!!! ERROR ON $sym ($text) ($opts)"
+    echo "!!!! BWIPP OUTPUT ($GSOUT):"
+    cat $GSOUT
+    echo "!!!! BWIP-JS OUTPUT ($JSOUT):"
+    cat $JSOUT
+    echo "!!!!"
+    exit 1
 fi
 
 exit 0
